name: Build Windows (Skip Sync and Deploy)

on:
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Preserve workflows
        run: |
          mkdir backup
          cp -r .github backup/

      - name: Sync with upstream
        shell: bash
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git remote add upstream https://github.com/earthjasonlin/portfolio.git
          git fetch upstream
          git checkout master

          rm -rf .github
          cp -r backup/.github ./
          git add .github
          git commit -m "Workflows" || echo "No changes"
          git remote set-url origin https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}.git
          

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Get version
        id: version
        shell: bash
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout -f portfolio-app/pom.xml)
          HASH=$(git rev-parse --short upstream/master)
          echo "FULL_VERSION=${VERSION}-${HASH}" >> $GITHUB_ENV
          echo "full_version=${VERSION}-${HASH}" >> $GITHUB_OUTPUT

      - name: Build with Maven
        shell: bash
        run: |
          export MAVEN_OPTS="-Xmx4g"
          mvn -f portfolio-app/pom.xml clean verify

      - name: Package Windows Product
        shell: pwsh
        run: |
          $productDir = "portfolio-product/target/products/name.abuchen.portfolio.product/win32/win32/x86_64/portfolio"
          $zipName = "PortfolioPerformance-${env:FULL_VERSION}-win32.win32.x86_64.zip"
          Compress-Archive -Path "$productDir/*" -DestinationPath $zipName

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: portfolio-performance-windows
          path: |
            PortfolioPerformance-*-win32.win32.x86_64.zip
